#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-commons-lang
Version  : 2.1
Release  : 1
URL      : https://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.1/commons-lang-2.1.jar
Source0  : https://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.1/commons-lang-2.1.jar
Source1  : https://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.1/commons-lang-2.1.pom
Source2  : https://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.3/commons-lang-2.3.jar
Source3  : https://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.3/commons-lang-2.3.pom
Source4  : https://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
Source5  : https://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.4/commons-lang-2.4.pom
Source6  : https://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
Source7  : https://repo.maven.apache.org/maven2/commons-lang/commons-lang/2.6/commons-lang-2.6.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-commons-lang-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-commons-lang package.
Group: Data

%description data
data components for the mvn-commons-lang package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-lang/commons-lang/2.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/commons-lang/commons-lang/2.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-lang/commons-lang/2.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/commons-lang/commons-lang/2.1

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-lang/commons-lang/2.3
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/commons-lang/commons-lang/2.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-lang/commons-lang/2.3
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/commons-lang/commons-lang/2.3

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-lang/commons-lang/2.4
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/commons-lang/commons-lang/2.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-lang/commons-lang/2.4
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/commons-lang/commons-lang/2.4

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-lang/commons-lang/2.6
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/commons-lang/commons-lang/2.6

mkdir -p %{buildroot}/usr/share/java/.m2/repository/commons-lang/commons-lang/2.6
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/commons-lang/commons-lang/2.6


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/commons-lang/commons-lang/2.1/commons-lang-2.1.jar
/usr/share/java/.m2/repository/commons-lang/commons-lang/2.1/commons-lang-2.1.pom
/usr/share/java/.m2/repository/commons-lang/commons-lang/2.3/commons-lang-2.3.jar
/usr/share/java/.m2/repository/commons-lang/commons-lang/2.3/commons-lang-2.3.pom
/usr/share/java/.m2/repository/commons-lang/commons-lang/2.4/commons-lang-2.4.jar
/usr/share/java/.m2/repository/commons-lang/commons-lang/2.4/commons-lang-2.4.pom
/usr/share/java/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
/usr/share/java/.m2/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.pom
